import {Alert} from "react-native";


const requestedCrypto = ["BTC",
    "ETH",
    "BNB",
    "USDT",
    "SOL",
    "ADA",
    "XRP",
    "DOT",
    "DOGE",
    "USDC",
    "SHIB",
    "LUNA",
    "AVAX",
    "UNI",
    "LINK",
    "WBTC",
    "BUSD",
    "LTC",
    "ALGO",
    "BCH",
    "VET",
    "ICP",
    "AXS",
    "CRO",
    "XLM",
    "THETA",
    "FIL",
    "TRX",
    "FTM",
    "FTT",
    "ETC",
    "BTCB",
    "DAI",
    "EGLD",
    "HBAR",
    "XTZ",
    "NEAR",
    "GRT",
    "CAKE",
    "XMR",
    "MANA",
    "AAVE",
    "EOS",
    "FLOW",
    "KLAY",
    "XEC",
    "RUNE",
    "MIOTA",
    "KSM",
    "PHB",
    "BSV",
    "ONE",
    "NEO",
    "HNT",
    "QNT",
    "LEO",
    "UST",
    "MKR",
    "WAVES",
    "CHZ",
    "AR",
    "AMP",
    "HOT",
    "BTT",
    "STX",
    "ENJ",
    "OMG",
    "SAND",
    "CELO",
    "COMP",
    "ZEC",
    "DASH",
    "TFUEL",
    "XEM",
    "CRV",
    "NEXO",
    "HT",
    "KDA",
    "SUSHI",
    "QTUM",
    "KCS",
    "BAT",
    "LRC",
    "OKB",
    "ICX",
    "DCR",
    "RVN",
    "SCRT",
    "AUDIO",
    "REV",
    "ZIL",
    "TEL",
    "YFI",
    "MINA",
    "TUSD",
    "SNX",
    "PERP",
    "XDC"]

const getData = async (url) => {
    try {
        const response = await fetch(url);
        return await response.json();
    } catch (err) {
        Alert.alert(
            "Erreur lors de la récupération des données",
            err.message
        );
    }
};

export const getCrypto = async () => {
    const cryptoIds = requestedCrypto.join(",")
    return await getData("https://api.nomics.com/v1/currencies/ticker?key=d9aed0030d0105a6a4d9a423720143a84824d3d4&ids=" + cryptoIds + "&convert=EUR")
}